export const menuItems = [
  {
    id: 1,
    category: "plats",
    title: "Attieke Garba",
    description: "Attieke avec poisson braisé",
    price: "32€",
    image: "/images/attieke.png",
  },
  {
    id: 2,
    category: "plats",
    title: "Riz d'Alex",
    description: "Riz d'Alex et son poisson braisé",
    price: "12€",
    image: "/images/riz-d-alex.png",
  },
  {
    id: 3,
    category: "plats",
    title: "Risotto aux Truffes",
    description: "Crémeux et parfumé, truffe noire fraîche",
    price: "28€",
    image: "/images/poulet.jpg",
  },
  {
    id: 4,
    category: "plats",
    title: "Côte de Bœuf",
    description: "Maturée 30 jours, légumes rôtis",
    price: "45€",
    image: "/images/poulet.jpg",
  },
  {
    id: 5,
    category: "desserts",
    title: "Sorbet Coco",
    description: "Sorbet coco aux saveurs antillaises",
    price: "10€",
    image: "/images/sorbet-coco.jpg",
  },
  {
    id: 6,
    category: "boissons",
    title: "Cocktail Maison",
    description: "Fruits frais, rhum premium",
    price: "14€",
    image: "/images/poulet.jpg",
  },
];
