export const menuItems = [
  {
    id: 1,
    category: "entrées",
    title: "Poulpe Grillé",
    description: "Purée de patate douce, huile d’olive",
    price: "32€",
    image: "/images/poulet.jpg",
  },
  {
    id: 2,
    category: "entrées",
    title: "Bruschetta",
    description: "Tomates fraîches, basilic, huile d’olive",
    price: "12€",
    image: "/images/poulet.jpg",
  },
  {
    id: 3,
    category: "plats",
    title: "Risotto aux Truffes",
    description: "Crémeux et parfumé, truffe noire fraîche",
    price: "28€",
    image: "/images/poulet.jpg",
  },
  {
    id: 4,
    category: "plats",
    title: "Côte de Bœuf",
    description: "Maturée 30 jours, légumes rôtis",
    price: "45€",
    image: "/images/poulet.jpg",
  },
  {
    id: 5,
    category: "desserts",
    title: "Tiramisu",
    description: "Mascarpone, cacao amer, café italien",
    price: "10€",
    image: "/images/poulet.jpg",
  },
  {
    id: 6,
    category: "boissons",
    title: "Cocktail Maison",
    description: "Fruits frais, rhum premium",
    price: "14€",
    image: "/images/poulet.jpg",
  },
];
