export const menuItems = [
  {
    id: 1,
    category: "plats",
    title: "Attieke Garba",
    description: "Attiéké à la semoule fine, accompagné de poisson braisé aux épices",
    price: "",
    image: "/images/attieke.png",
  },
  {
    id: 2,
    category: "plats",
    title: "Riz d'Alex",
    description: "Riz parfumé maison servi avec poisson braisé et sa sauce aromatique",
    price: "",
    image: "/images/riz-d-alex.png",
  },
  {
    id: 3,
    category: "plats",
    title: "Spaghetti omelette",
    description: "Spaghettis à l'omelette, recette signature",
    price: "",
    image: "/images/spaghetti-à-loeuf.jpg",
  },
  {
    id: 4,
    category: "entrées",
    title: "Salade composée",
    description: "Salade généreuse aux légumes de saison",
    price: "",
    image: "/images/salade.jpg",
  },
  {
    id: 5,
    category: "desserts",
    title: "Sorbet Coco",
    description: "Sorbet coco frais, notes des Antilles",
    price: "",
    image: "/images/sorbet-coco.webp",
  },
  {
    id: 6,
    category: "boissons",
    title: "Bière et boissons",
    description: "Sélection de bières artisanales et boissons fraîches",
    price: "",
    image: "/images/boissons.png",
  },
  {
    id: 7,
    category: "entrées",
    title: "Avocat crudités",
    description: "Avocat crémeux et crudités croquantes",
    price: "",
    image: "/images/avocat-crudites.png",
  },
  {
    id: 8,
    category: "desserts",
    title: "Salade de fruits",
    description: "Assortiment de fruits de saison",
    price: "10€",
    image: "/images/salade-fruits.webp",
  },
  {
    id: 9,
    category: "plats",
    title: "Amiwo",
    description: "Semoule de maïs avec poulet braisé et sauce tomate maison",
    price: "",
    image: "/images/Amiwo-2000.webp",
  },
  {
    id: 10,
    category: "plats",
    title: "Poisson braisé",
    description: "Poisson entier braisé aux épices, fraîcheur du marché",
    price: "",
    image: "/images/poisson-braise.jpg",
  },
  {
    id: 11,
    category: "plats",
    title: "Egousi soup",
    description: "Soupe traditionnelle d'egousi et agbeli, générosité africaine",
    price: "",
    image: "/images/egousi-agbeli.webp",
  },
  {
    id: 12,
    category: "entrées",
    title: "Accras",
    description: "Accras de morue croustillants, recette des îles",
    price: "",
    image: "/images/accras.jpg",
  },
];
